### ISSUE TITLE
full search bar

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#12]
http://10consulting.com/2013/03/06/jekyll-and-lunr-js-static-websites-with-powerful-full-text-search-using-javascript/

Needs plugin, another reason to host files on github and mirror on other hosting site, amazon etc,

**Comment by IsabelleNastasia** [comment]
+1

On Tuesday, October 15, 2013, Maya wrote:

> http://10consulting.com/2013/03/06/jekyll-and-lunr-js-static-websites-with-powerful-full-text-search-using-javascript/
> 
> Needs plugin, another reason to host files on github and mirror on other
> hosting site, amazon etc,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/12
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Director of Development - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Search bar shows up and take user to /search page, but I need to build the plugin so the searches work.
Steps: Need to install nokogiri and build the plugin: https://github.com/slashdotdash/jekyll-lunr-js-search#requirements

Remember this doesn't work on Github Pages because it runs Jekyll in safe mode. Search bar will work once it is hosted elsewhere.

**Comment by mayarichman** [comment]
Search not pulling up entries and autopopulating the right divs. Changed the url location of search.json in script within the search page and in the lunar.js default variables.

**Comment by mayarichman** [comment]
Search is working well now. It is a little slower than I'd like, so I can investigate that. Test it out at [thewildcity.org](thewildcity.org).

**Comment by mayarichman** [comment]
Unless the search bar presents another problem, I will close this issue.
