### ISSUE TITLE
"pitch" page with editor information

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#17]

**Comment by mayarichman** [comment]
@IsabelleNastasia Who will be on this page? Any copy about pitches (formats, themes etc) to put in and any ideas on what you'd like it to look like?

**Comment by IsabelleNastasia** [comment]
Word. Is it possible to have a form that ppl can fill out that
automatically goes to my isabelle@youngist.org email?

I can also sent the wording for this page tonight

**Comment by mayarichman** [comment]
Great. Yeah, that's is probably possible, just need to find some tutorials on how to do that securely. :+1:

**Comment by mayarichman** [comment]
The pitch page links to the contact section of about which has every editors email available. When you click on the email it opens the default OS mail client.

@IsabelleNastasia Are we still interested in having a form?

**Comment by mayarichman** [comment]
Whoops! Didn't mean to close.

**Comment by mayarichman** [comment]
Pitch page now links to about page contact section. Closing.
