### ISSUE TITLE
take action page

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#22]

**Comment by mayarichman** [comment]
Needs share button. Closing.

**Comment by IsabelleNastasia** [comment]
I don't want to give you more work but what if we did something more like
this?
http://colorlines.com/action/

have a row of "petitions" and stuff and then a scroll down of "action-based
stories"?

feel free to push back on that.

On Mon, Jan 6, 2014 at 7:03 PM, Maya notifications@github.com wrote:

> Needs share button. Closing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/22#issuecomment-31701092
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Would we be posting action based stories?

**Comment by IsabelleNastasia** [comment]
Yeah

**Comment by mayarichman** [comment]
We could have a list of pieces written that are tagged action, I don't
imagine it being very difficult. I'm going to put that on the backburner
for now though because I just built the action page design that Tom asked
for, so I want to prioritize other things right now.

**Comment by IsabelleNastasia** [comment]
Yup

**Comment by mayarichman** [comment]
Action posts will be petitions, rallys, calls to congress etc. Other article posts that are currently relevant to actions can be tagged action in the category and but will be regular post format.

**Comment by mayarichman** [comment]
Examples of metadata style for action posts that are not petitions:

``` yaml
categories:
- video
- action
```

``` yaml
categories:
- video
- article
```
