### ISSUE TITLE
space between footer and media content

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#24]
Maybe related to use of clearfix.

![screen shot 2013-10-23 at 5 07 25 pm](https://f.cloud.github.com/assets/1129086/1394380/9c8fbde0-3c28-11e3-9771-dee28f21dc75.png)

**Comment by IsabelleNastasia** [comment]
whats a clearfix?

On Wed, Oct 23, 2013 at 5:18 PM, Maya notifications@github.com wrote:

> Maybe related to use of clearfix.
> 
> [image: screen shot 2013-10-23 at 5 07 25 pm]https://f.cloud.github.com/assets/1129086/1394380/9c8fbde0-3c28-11e3-9771-dee28f21dc75.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/24
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Director of Development - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
I will explain it poortly!

Check this: stackoverflow.com/questions/9543541/what-does-the-clearfix-class-do-in-css

**Comment by mayarichman** [comment]
Problem fixed with container rather than clearfix. Closing.
