### ISSUE TITLE
style and place arrows for carousel

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#28]
![screen shot 2013-10-23 at 5 06 57 pm](https://f.cloud.github.com/assets/1129086/1394426/3b449302-3c29-11e3-96e3-c4c7cacde54e.png)

**Comment by IsabelleNastasia** [comment]
love.

On Wed, Oct 23, 2013 at 5:22 PM, Maya notifications@github.com wrote:

> [image: screen shot 2013-10-23 at 5 06 57 pm]https://f.cloud.github.com/assets/1129086/1394426/3b449302-3c29-11e3-96e3-c4c7cacde54e.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/28
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Director of Development - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Done.
