### ISSUE TITLE
multiple contributors

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#3]
Just a reminder/heads up.

The current design doesn't account for multiple contributors, with multiple bios.

**Comment by mayarichman** [comment]
This is still something I am unsure about. Will most articles have only one contributor @IsabelleNastasia?

**Comment by IsabelleNastasia** [comment]
Most pieces are one contributor but we should talk about this because there
are exceptions.

**Comment by IsabelleNastasia** [comment]
What do you suggest?

**Comment by mayarichman** [comment]
Maybe a byline with both or all and just one persons image? Not sure.
Something to look at and discuss. Current design is oriented just to one
person.

**Comment by IsabelleNastasia** [comment]
I wonder if Tom could throw together one more design?  Welp.

**Comment by IsabelleNastasia** [comment]
Otherwise, yes, I think one byline with both works.

On Tue, Nov 26, 2013 at 4:59 PM, Isabelle Nastasia <
isabelle.nastasia@gmail.com> wrote:

> I wonder if Tom could throw together one more design?  Welp.
> On Nov 26, 2013 4:58 PM, "Maya" notifications@github.com wrote:
> 
> > Maybe a byline with both or all and just one persons image? Not sure.
> > Something to look at and discuss. Current design is oriented just to one
> > person.
> > On Nov 26, 2013 4:56 PM, "IsabelleNastasia" notifications@github.com
> > wrote:
> > 
> > > What do you suggest?
> > > On Nov 26, 2013 4:26 PM, "Isabelle Nastasia" <
> > > isabelle.nastasia@gmail.com>
> > > 
> > > wrote:
> > > 
> > > > Most pieces are one contributor but we should talk about this because
> > > > there are exceptions.
> > > > On Nov 26, 2013 4:22 PM, "Maya" notifications@github.com wrote:
> > > > 
> > > > > This is still something I am unsure about. Will most articles have
> > > > > only
> > > > > one contributor @IsabelleNastasia <
> > > > > https://github.com/IsabelleNastasia>?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/youngist/clean-blog/issues/3#issuecomment-29335265>
> > > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/youngist/clean-blog/issues/3#issuecomment-29338206>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/3#issuecomment-29338571
> > .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
For each post the editor will put whichever contributor information makes more sense and will make a bio page for them as well, if that makes sense. In the post content, the editor include a byline with all contributors names.

Closing.
