### ISSUE TITLE
integrate social media

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#32]
Need to make sure twitter and Facebook have all the data and embeds to share easily

**Comment by mayarichman** [comment]
http://www.codehandling.com/2012/11/social-marketing-of-your-webpage-on.html?m=1

**Comment by mayarichman** [comment]
https://developers.google.com/+/web/snippet/?hl=en

**Comment by mayarichman** [comment]
https://dev.twitter.com/docs/tweet-button

**Comment by IsabelleNastasia** [comment]
This is so cool.

Can you send me a list of things you need from me so I can do them all
tonight?

On Thursday, November 21, 2013, Maya wrote:

> https://dev.twitter.com/docs/tweet-button
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/32#issuecomment-29025085
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Facebook developer bugs are preventing me from making youngist an app that would allow me to put in the share button.

Need an APP ID but can’t seem to make an account, resource with the same problem, http://stackoverflow.com/questions/7874654/facebook-developer-account-verify

**Comment by mayarichman** [comment]
Solved problem related to the referring url. Tweets may be too long with via element and full title/link. Closing for now.
