### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#33]
Need to find a place to host site that can be pulled from github changes through prose

**Comment by mayarichman** [comment]
Ask [Floh](https://twitter.com/flohdot) about heroku and amazon hosting services for static sites that are mirrored from github.

**Comment by mayarichman** [comment]
Prose + Github + Heroku

https://github.com/himynameisjonas/jekyll-heroku-unicorn

http://jonasforsberg.se/2012/07/22/jekyll-heroku-unicorn

https://devcenter.heroku.com/articles/getting-started-with-ruby#prerequisites

https://devcenter.heroku.com/articles/git

http://stackoverflow.com/questions/9305370/rails-3-2-heroku-push-rejected-no-cedar-supported-app-detected

**Comment by IsabelleNastasia** [comment]
need any help with this?

On Mon, Dec 30, 2013 at 12:39 PM, Maya notifications@github.com wrote:

> Prose + Github + Heroku
> 
> https://github.com/himynameisjonas/jekyll-heroku-unicorn
> 
> http://jonasforsberg.se/2012/07/22/jekyll-heroku-unicorn
> 
> https://devcenter.heroku.com/articles/getting-started-with-ruby#prerequisites
> 
> https://devcenter.heroku.com/articles/git
> 
> http://stackoverflow.com/questions/9305370/rails-3-2-heroku-push-rejected-no-cedar-supported-app-detected
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/33#issuecomment-31367398
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Trying to set it up for my computer now. I'll let you know, although it's
one of those big tech things.

**Comment by IsabelleNastasia** [comment]
Totally.

Sorry but can you resend me the list of stuff you need from me? I keep
misplacing it :-/

**Comment by mayarichman** [comment]
No problem. I'll make a super clear list today.

**Comment by mayarichman** [comment]
Need:
- banner photos for about, donate, pitch
  pageshttps://github.com/youngist/clean-blog/issues/38
- text for donate page
- disqus password to integrate into the site
- Ads →find something easier than adzerk
- ask contributors for their preferred bio photos and other other
  information https://github.com/youngist/clean-blog/issues/4
- Large collection of all information into google spreadsheet

Example:

title: Maya Richman, Web Developer

position: staff

excerpt: souvlaki, summer, swimming and something else

contributorimage:
http://media.tumblr.com/30a5a903022d519cfbfad525904da6dd/tumblr_inline_mocar7RARS1rkj9dw.jpg

coverphoto:
http://static3.wikia.nocookie.net/__cb20120722221615/disney/images/d/da/Darn_Cat_003.jpg

bio: "Maya means illusion in Sanskrit but she has a tangible form that
currently resides in Montreal, originally hailing from Venice, California.
Stumbling and scraping her knees on a computer science minor while studying
international development, she found herself programming, embracing open
source, Github and digital storytelling. She built custom map-based
websites with <a href='http://www.mapbox.com/'>Mapbox</a> and the American
Red Cross and dabbles in graphic design, video editing, and improvisational
electronic music performance. You can send her sparkly gifs at <a href='
https://twitter.com/mayarichman'>@mayarichman</a>."

contributortwitter: mayarichman

contributorage: 22

birthdate: 01-17-1991

contributors:
- Maya Richman
- google spreadsheet of all information needed for each post for the new
  site i.e. migration
- who is the primary author, if there are several contributors

**Comment by mayarichman** [comment]
Made serious progress with hosting today. Successfully created a webhook that linked from clean-blog repo to Ubuntu EC2 Instance but site was not successfully building.

**Comment by IsabelleNastasia** [comment]
Awesome!

On Sat, Feb 22, 2014 at 6:18 PM, Maya notifications@github.com wrote:

> Made serious progress with hosting today. Successfully created a webhook
> that linked from clean-blog repo to Ubuntu EC2 Instance but site was not
> successfully building.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/33#issuecomment-35818411
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
@catachresis Have you ever used Amazon Web Services and configured a server?

I am working off of the instructions found [here](https://github.com/developmentseed/jekyll-hook) to configure a server and build the site.

**Comment by mayarichman** [comment]
I've got this running: http://107.170.53.200/

@IsabelleNastasia I am a newb, so if you can access it and the tags work, hallelujah! There are still things to be done. I am changing the domain name to one I bought: thewildcity.org and making sure that changes made on Github are **automatically** updated. 

Currently, when I run a script on my local machine and open the port 8080 and then link the webhook to the ip address on the same port, all changes are updated! But ideally it is not linked through a local port. The server only costs $5 a month.

**Comment by IsabelleNastasia** [comment]
Cool.  Wanna chat on google hang this afternoon and run thru it together? I
can do 4pm or later.  If not, tomorrow

**Comment by mayarichman** [comment]
Tomorrow would be better. I'm not ready to ship, just making my way.

**Comment by IsabelleNastasia** [comment]
K

**Comment by mayarichman** [comment]
It's working at [http://thewildcity.org/](http://thewildcity.org/) which is a domain I purchased. I am dealing with one more detail, that ensures that I don't have to run anything on my computer for changes to be updated. We will have to switch youngist.org nameserver to point to where mine is hosted. I will message Alex about that. Besides that, the hosting debacle is finished!

**Comment by mayarichman** [comment]
Boom! Changes are updated from github! Although the page doesn't appear immediately ( < 1 min), it will update from changes on Prose.io. I will flag new issues if I find them, otherwise, after all other little bugs are done, we can switch the domain over.

**Comment by mayarichman** [comment]
Done! Closing.

**Comment by IsabelleNastasia** [comment]
What does this mean?

**Comment by mayarichman** [comment]
It means that users can edit the site and it updates the domain
thewildcity.org. still need to move the domain name to youngist ( which is
another issue).

**Comment by IsabelleNastasia** [comment]
K
