### ISSUE TITLE
default style post for soundcloud and youtube posts

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#35]
As discussed, the sound embed should be bigger, cover sized, from soundcloud for posts with transcript.

**Comment by mayarichman** [comment]
@IsabelleNastasia How's the size?

![](http://f.cl.ly/items/043K3M371C2S0O0k1j1e/Screen%20Shot%202013-12-03%20at%2012.07.14%20PM.png)

**Comment by IsabelleNastasia** [comment]
I  can't respond until later but will by the end of the day

**Comment by mayarichman** [comment]
No problem, just queuing up somethings.

**Comment by mayarichman** [comment]
Posts with the category video will load with the videourl given as the main image, otherwise a featured photo and the rest of the content is shown. Closing for now.
