### ISSUE TITLE
tag box

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#37]
@IsabelleNastasia How does this look? More tags less spacing.

![](http://f.cl.ly/items/0Y3c0O0D123b3O0P2004/Screen%20Shot%202013-12-03%20at%2011.58.31%20AM.png)

**Comment by IsabelleNastasia** [comment]
PERFECT.

On Tue, Dec 3, 2013 at 11:59 AM, Maya notifications@github.com wrote:

> @IsabelleNastasia https://github.com/IsabelleNastasia How does this
> look? More tags less spacing.
> 
> http://f.cl.ly/items/0Y3c0O0D123b3O0P2004/Screen%20Shot%202013-12-03%20at%2011.58.31%20AM.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/37
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by mayarichman** [comment]
Showing fewer tags now but looks better in other layouts. Closing for now.
