### ISSUE TITLE
ask contributors for their preferred bio photos

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#4]
We need everyone to submit their image choices for that header that is currently umbrellas on contributor pages. e.g. http://youngist.github.io/clean-blog/maya-richman/

**Comment by IsabelleNastasia** [comment]
If you give me a list of things we need from all the contributors I can
send out an email ASAP.

On Wed, Jul 10, 2013 at 4:03 PM, Maya notifications@github.com wrote:

> We need everyone to submit their image choices for that header that is
> currently umbrellas on contributor pages. e.g.
> http://youngist.github.io/clean-blog/maya-richman/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/4
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Director of Development - New York Students Rising (NYSR)
917 608 2747

**Comment by mayarichman** [comment]
Will do!

**Comment by mayarichman** [comment]
Actionable Item: We need to make sure a master google doc exists with all the information as we add contributors that any editor can quickly grab everything.

**Comment by IsabelleNastasia** [comment]
I'll make a Google form

**Comment by mayarichman** [comment]
This is being taken care of by @IsabelleNastasia <3 Closing.
