### ISSUE TITLE
copy edit all pages

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#57]

**Comment by mayarichman** [comment]
@IsabelleNastasia All about, masthead etc. could be copy-edited at any point.

**Comment by IsabelleNastasia** [comment]
I'll make this happen tomorrow

**Comment by mayarichman** [comment]
Awesome. Thanks.

**Comment by mayarichman** [comment]
All pages copy edited. New bios still need to be added. Closing.
