### ISSUE TITLE
archive page

### ISSUE THREAD

**Issue by awstevens** [youngist/clean-blog#7]
@Acker1021 Just wanna flag that we're also going to need a page design for a historical post Archive

**Comment by IsabelleNastasia** [comment]
And the masthead too @acker1021.

On Wed, Jul 10, 2013 at 6:54 PM, Alex Stevens notifications@github.comwrote:

> @Acker1021 https://github.com/Acker1021 Just wanna flag that we're also
> going to need a page design for a historical post Archive
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/7
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Director of Development - New York Students Rising (NYSR)
917 608 2747

**Comment by mayarichman** [comment]
Spoke with @IsabelleNastasia and determined for now that it is not necessary because we already have category tags. Closing for now.
