### ISSUE TITLE
Adding Facebook Open Graph tags to post pages

### ISSUE THREAD

**Issue by awstevens** [youngist/clean-blog#8]
via Facebook for Developers, <a href="https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/#tags">"Maximizing Distribution for Media Content"</a>: 

> <strong> 3. Use proper Open Graph tags and large images to generate great previews and drive distribution
> 
> Open Graph tags are included in your page’s HTML and allow the Facebook Crawler to generate previews when your content is shared on Facebook.
> 
> We give examples below, but the basic Open Graph tags you should implement are:
> - og:title – The title of your article, excluding any branding.
> - og:site_name - The name of your website. Not the URL, but the name. (i.e. "IMDb" not "imdb.com".)
> - og:url – This URL serves as the unique identifier for your post. It should match your canonical URL used for SEO, and it should not include any session variables, user identifying parameters, or counters. If you use this improperly, likes and shares will not be aggregated for this URL and will be spread across all of the variations of the URL.
> - og:description – A detailed description of the piece of content, usually between 2 and 4 sentences. This tag is technically optional, but can improve the rate at which links are read and shared.
> - og:image – This is an image associated with your media. We suggest that you use an image of at least 200x200 pixels. However, bigger is better, so if you have a 1500x1500 image that you can use, please use it. We'll downsample and crop it for for people using smaller-resolution devices but will use it on a larger device. The larger this image is, the more likely it will be used when sharing stories on Facebook. (Note: image sizes must be no more than 5MB in size.)
> - fb:app_id – The unique ID that lets Facebook know the identity of your site. This is crucial for Facebook Insights to work properly. Please see our Insights documentation to learn more.
> 
> In addition, you might consider implementing some other types to improve distribution and engagement:
> - og:type - Different types of media will change how your content shows up in Facebook's newsfeed. There are a number of different common object types already defined. If you don't specify a type, the default will be website. You can also specify your own types via Open Graph.
> - og:locale - The locale of the resource. The default is en_US. You can also use the  og:locale:alternate to reflect that you have other available language translations available as well. See our Internationalization and Open Graph Internationalization pages for examples and information.
> - article:author - This property links to the authors of the article. The target of this can be either a Facebook Profile or a Facebook Page and Facebook will likely offer a chance to follow that author when it's displayed in the news feed. (Note that your authors should have follow enabled so that people can follow them.)
> - article:publisher - This property links to the publisher of the article. The target of this property must be a Facebook Page. When displayed in the news feed, Facebook may offer the ability to like the publisher.

See <a href="https://developers.facebook.com/docs/opengraph/howtos/maximizing-distribution-media-content/#tags">"Maximizing Distribution for Media Content"</a> for examples.

**Comment by mayarichman** [comment]
Seems to be picking up everything but the photo. Placing the metatags in the header instead of the body.

Helpful facebook debugger: https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fyoungist.github.io%2Fclean-blog%2Fmeet-the-editors-queen-arsem-omalley%2F

Closing for now.
