### ISSUE TITLE
make formal tags list

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#85]
@IsabelleNastasia Queen and I met and talked about making a more clear document with commonly used tags. Just wanted to make an issue so we are sure we do this.

**Comment by qaween** [comment]
was there a preliminary list we had going?

On Thu, Mar 13, 2014 at 1:00 PM, Maya notifications@github.com wrote:

> @IsabelleNastasia https://github.com/IsabelleNastasia Queen and I met
> and talked about making a more clear document with commonly used tags. Just
> wanted to make an issue so we are sure we do this.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/85
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
Tags now accessible [here](https://docs.google.com/spreadsheet/ccc?key=0AvthiCJscpOFdFgxM1ZGTEs4TGRmMWtnRWxJS2tyRHc&usp=drive_web#gid=0). @IsabelleNastasia  is working on updating them. Can I close this?

**Comment by qaween** [comment]
Yeah working on them now

**Comment by mayarichman** [comment]
Great. Saw the edits. Good work! Closing.
