### ISSUE TITLE
Interview with Julio broken link

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#86]
@IsabelleNastasia 

There is no accessible mp3 on youngist.org for the interview of Julio by Nia. Does anyone have this interview in an email or something else?

http://youngist.org/post/51730036034/undocumented-and-awkward-an-interview-with-julio-salgado

http://traffic.libsyn.com/artactivistnia/Julio_edited_1-2_1.mp3

**Comment by IsabelleNastasia** [comment]
oof. i'll ask nia.

On Tue, Mar 18, 2014 at 4:57 PM, Maya notifications@github.com wrote:

> @IsabelleNastasia https://github.com/IsabelleNastasia
> 
> There is no accessible mp3 on youngist.org for the interview of Julio by
> Nia. Does anyone have this interview in an email or something else?
> 
> http://youngist.org/post/51730036034/undocumented-and-awkward-an-interview-with-julio-salgado
> 
> http://traffic.libsyn.com/artactivistnia/Julio_edited_1-2_1.mp3
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by qaween** [comment]
I have it, can dropbox it to you Maya?

On Tue, Mar 18, 2014 at 4:59 PM, IsabelleNastasia
notifications@github.comwrote:

> oof. i'll ask nia.
> 
> On Tue, Mar 18, 2014 at 4:57 PM, Maya notifications@github.com wrote:
> 
> > @IsabelleNastasia https://github.com/IsabelleNastasia
> > 
> > There is no accessible mp3 on youngist.org for the interview of Julio by
> > Nia. Does anyone have this interview in an email or something else?
> > 
> > http://youngist.org/post/51730036034/undocumented-and-awkward-an-interview-with-julio-salgado
> > 
> > http://traffic.libsyn.com/artactivistnia/Julio_edited_1-2_1.mp3
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/youngist/clean-blog/issues/86>
> > .
> 
> ## 
> 
> Isabelle Nastasia
> PGP: She/her/hers
> Cofounder/Managing Editor - youngist.org
> Communications Strategy - New York Students Rising (NYSR)
> Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> 917 608 2747
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86#issuecomment-37987323
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by qaween** [comment]
Or google drive? (Cloud doesn't work on my comp)

On Tue, Mar 18, 2014 at 5:00 PM, Queen Arsem-O'Malley <
qarsemomalley@gmail.com> wrote:

> I have it, can dropbox it to you Maya?
> 
> On Tue, Mar 18, 2014 at 4:59 PM, IsabelleNastasia <
> notifications@github.com> wrote:
> 
> > oof. i'll ask nia.
> > 
> > On Tue, Mar 18, 2014 at 4:57 PM, Maya notifications@github.com wrote:
> > 
> > > @IsabelleNastasia https://github.com/IsabelleNastasia
> > > 
> > > There is no accessible mp3 on youngist.org for the interview of Julio
> > > by
> > > Nia. Does anyone have this interview in an email or something else?
> > > 
> > > http://youngist.org/post/51730036034/undocumented-and-awkward-an-interview-with-julio-salgado
> > > 
> > > http://traffic.libsyn.com/artactivistnia/Julio_edited_1-2_1.mp3
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/youngist/clean-blog/issues/86>
> > > .
> > 
> > ## 
> > 
> > Isabelle Nastasia
> > PGP: She/her/hers
> > Cofounder/Managing Editor - youngist.org
> > Communications Strategy - New York Students Rising (NYSR)
> > Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> > 917 608 2747
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86#issuecomment-37987323
> > .
> 
> ## 
> 
> Queen Arsem-O'Malley
> PGP: she/her/hers
> 514-710-8878
> qarsemomalley@gmail.com | @qaween

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
Yeah just put it on google drive!

**Comment by qaween** [comment]
just shared it, lemme know if it doesn't work

On Tue, Mar 18, 2014 at 5:01 PM, Maya notifications@github.com wrote:

> Yeah just put it on google drive!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86#issuecomment-37987589
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
It works but I just realized we want it on the soundcloud so we can just embed it. Can you do this @qaween?

**Comment by qaween** [comment]
Do we have an account or should I make one...?

On Tue, Mar 18, 2014 at 5:29 PM, Maya notifications@github.com wrote:

> It works but I just realized we want it on the soundcloud so we can just
> embed it. Can you do this @qaween https://github.com/qaween?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86#issuecomment-37990969
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
We have one. Ask alex?

**Comment by qaween** [comment]
https://soundcloud.com/youngist-org/undocumented-and-awkward-an

On Tue, Mar 18, 2014 at 7:57 PM, Maya notifications@github.com wrote:

> We have one. Ask alex?
> 
> On Mar 18, 2014 6:47 PM, "Queen" notifications@github.com wrote:
> 
> > Do we have an account or should I make one...?
> > 
> > On Tue, Mar 18, 2014 at 5:29 PM, Maya notifications@github.com wrote:
> > 
> > > It works but I just realized we want it on the soundcloud so we can
> > > just
> > > embed it. Can you do this @qaween https://github.com/qaween?
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/youngist/clean-blog/issues/86#issuecomment-37990969>
> > > 
> > > .
> > 
> > ## 
> > 
> > Queen Arsem-O'Malley
> > PGP: she/her/hers
> > 514-710-8878
> > qarsemomalley@gmail.com | @qaween
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/youngist/clean-blog/issues/86#issuecomment-37998530>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/86#issuecomment-38003777
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
Awesome! Added!

**Comment by mayarichman** [comment]
Looks great. Thanks @qaween. Closing.
