### ISSUE TITLE
small tasks

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#87]
- ~~hover over links and make them white in about/masthead etc.~~
- ~~fewer tags on cece piece~~
- ~~info for gallery images don't say anything~~
- ~~fix bug in stonewall gallery post~~
- ~~look at site on ie?!~~
-  ~~change size of search bar in mobile~~

**Comment by qaween** [comment]
fixed cece, add hira photo

On Thu, Mar 20, 2014 at 11:26 AM, Maya notifications@github.com wrote:

> - hover over links and make them white in about/masthead etc.
> - remove padding for tag h4 so "published on" is closed together
> - remove padding above in title on posts
> - fewer tags on cece piece
> - info for gallery images don't say anything
> - look at site on ie?!
> - change size of search bar in mobile
> - add search icon to search bar
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/87
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by IsabelleNastasia** [comment]
how is this going? can i help?

On Thu, Mar 20, 2014 at 1:39 PM, Queen notifications@github.com wrote:

> fixed cece, add hira photo
> 
> On Thu, Mar 20, 2014 at 11:26 AM, Maya notifications@github.com wrote:
> 
> > - hover over links and make them white in about/masthead etc.
> > - remove padding for tag h4 so "published on" is closed together
> > - remove padding above in title on posts
> > - fewer tags on cece piece
> > - info for gallery images don't say anything
> > - look at site on ie?!
> > - change size of search bar in mobile
> > - add search icon to search bar
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/youngist/clean-blog/issues/87>
> > .
> 
> ## 
> 
> Queen Arsem-O'Malley
> PGP: she/her/hers
> 514-710-8878
> qarsemomalley@gmail.com | @qaween
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/87#issuecomment-38197831
> .

## 

Isabelle Nastasia
PGP: She/her/hers
Cofounder/Managing Editor - youngist.org
Communications Strategy - New York Students Rising (NYSR)
Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
917 608 2747

**Comment by qaween** [comment]
can we move Nia King selfie track to the youngist soundcloud account so we
can have all sound in one place?

On Thu, Mar 20, 2014 at 1:42 PM, IsabelleNastasia
notifications@github.comwrote:

> how is this going? can i help?
> 
> On Thu, Mar 20, 2014 at 1:39 PM, Queen notifications@github.com wrote:
> 
> > fixed cece, add hira photo
> > 
> > On Thu, Mar 20, 2014 at 11:26 AM, Maya notifications@github.com wrote:
> > 
> > > - hover over links and make them white in about/masthead etc.
> > > - remove padding for tag h4 so "published on" is closed together
> > > - remove padding above in title on posts
> > > - fewer tags on cece piece
> > > - info for gallery images don't say anything
> > > - look at site on ie?!
> > > - change size of search bar in mobile
> > > - add search icon to search bar
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/youngist/clean-blog/issues/87>
> > > 
> > > .
> > 
> > ## 
> > 
> > Queen Arsem-O'Malley
> > PGP: she/her/hers
> > 514-710-8878
> > qarsemomalley@gmail.com | @qaween
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/youngist/clean-blog/issues/87#issuecomment-38197831>
> > .
> 
> ## 
> 
> Isabelle Nastasia
> PGP: She/her/hers
> Cofounder/Managing Editor - youngist.org
> Communications Strategy - New York Students Rising (NYSR)
> Twitter: @IzzyNastasia; Instagram: IsabelleNastasia
> 917 608 2747
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youngist/clean-blog/issues/87#issuecomment-38198244
> .

## 

Queen Arsem-O'Malley
PGP: she/her/hers
514-710-8878
qarsemomalley@gmail.com | @qaween

**Comment by mayarichman** [comment]
Closing.
